In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
from sklearn.model_selection import train_test_split

In [3]:
import shap 

In [4]:
train_path = "../data/local_train.csv"
test_path = "../data/local_test.csv"

In [5]:
from lightgbm import LGBMClassifier

In [6]:
import hashlib

In [7]:
s="A"
int(hashlib.sha256(s.encode('utf-8')).hexdigest(), 16) % 10**2

45

In [8]:
def hash_cat(s):
    return int(hashlib.sha256(s.encode('utf-8')).hexdigest(), 16) % 10**3

In [9]:
# x = ['A', "b"]


In [10]:
# x.index('c')

In [11]:
cat_dict = []
def hash_cat_two(s):
    if s not in cat_dict:
        cat_dict.append(s)
    return cat_dict.index(s)

In [12]:
import pandas as pd

In [13]:
!ls ../data/

local_test.csv	local_train.csv  sample_submission.csv	test.csv  train.csv


In [14]:
df_train = pd.read_csv(train_path)
df_test = pd.read_csv(test_path)


In [15]:
len(df_train)

180000

In [16]:
df_train.head()

id cat0 cat1 cat2 cat3 cat4 cat5 cat6 cat7 cat8  ...     cont2  \
0    4700    B    F    A    B    E   BQ    A    N   BL  ...  0.236103   
1  453468    A    F    G    C    G   BI    A    U   AE  ...  0.627595   
2  369751    A    K    G    A    D   BU    A    E    Y  ...  0.568753   
3   69873    B    I    A    A    E   BI    A    Y   AU  ...  0.775825   
4  170717    A    M    A    B    F   BI    I   AH   BM  ...  0.256564   

      cont3     cont4     cont5     cont6     cont7     cont8     cont9  \
0  0.316480  0.600188  0.192628  0.423268  0.176169  0.288662  0.793823   
1  0.657871  0.285636  0.735430  0.624774  0.624786  0.702093  0.305428   
2  0.790244  0.829496  0.015555  0.201568  0.786024  0.385816  0.431418   
3  0.822142  0.796378  0.680048  0.246919  0.877006  0.611704  0.839066   
4  0.579400  0.291327  0.737406  0.579729  0.290138  0.351962  0.269911   

     cont10 target  
0  0.315937      0  
1  0.509672      0  
2  0.953504      0  
3  0.934136      0  
4  0.308573      1  

[5 rows x 32 columns]

In [17]:
from sklearn.preprocessing import OrdinalEncoder, LabelEncoder

In [18]:
df_train.columns

Index(['id', 'cat0', 'cat1', 'cat2', 'cat3', 'cat4', 'cat5', 'cat6', 'cat7',
       'cat8', 'cat9', 'cat10', 'cat11', 'cat12', 'cat13', 'cat14', 'cat15',
       'cat16', 'cat17', 'cat18', 'cont0', 'cont1', 'cont2', 'cont3', 'cont4',
       'cont5', 'cont6', 'cont7', 'cont8', 'cont9', 'cont10', 'target'],
      dtype='object')

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
# ?train_test_split

In [21]:
cat_col = ['cat0', 'cat1', 'cat2', 'cat3', 'cat4', 'cat5', 'cat6', 'cat7',
       'cat8', 'cat9', 'cat10', 'cat11', 'cat12', 'cat13', 'cat14', 'cat15',
       'cat16', 'cat17', 'cat18']
cont_col = ['cont0', 'cont1', 'cont2', 'cont3', 'cont4',
       'cont5', 'cont6', 'cont7', 'cont8', 'cont9', 'cont10']

In [22]:
for col in cat_col:
    encoder = LabelEncoder()
    # encoder.fit(list(df_train[col]) + list(df_test[col]))
    encoder.fit(list(df_train[col].values) + list(df_test[col].values))
    df_train[col] = encoder.transform(df_train[col].values)
    df_test[col] = encoder.transform(df_test[col].values)
    print("done ", col)

done  cat0
done  cat1
done  cat2
done  cat3
done  cat4
done  cat5
done  cat6
done  cat7
done  cat8
done  cat9
done  cat10
done  cat11
done  cat12
done  cat13
done  cat14
done  cat15
done  cat16
done  cat17
done  cat18


In [23]:
X = df_train.drop(["id", "target"], axis=1)
y = df_train["target"]


In [24]:
X.shape

(180000, 30)

In [25]:
y.shape

(180000,)

In [26]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=111)

In [27]:
import lightgbm as gbm

In [28]:
df_train["cat0"].unique()

array([1, 0])

https://www.kaggle.com/sayantansadhu/lgbm-with-hyper-parameter-tuning-using-optuna

In [29]:
lgbm_params = {
    'boosting': 'gbdt',          # dart (drop out trees) often performs better
    'application': 'binary',     # Binary classification
    'learning_rate': 0.02,       # Learning rate, controls size of a gradient descent step
    'min_data_in_leaf': 100,      # Data set is quite small so reduce this a bit
    'feature_fraction': 0.7,     # Proportion of features in each boost, controls overfitting
    'metric': 'binary_logloss',  # Area under ROC curve as the evaulation metric,
    'lambda_l1': 5e-05, 
     'lambda_l2': 1.35e-08, 
     'num_leaves': 216, 
     'feature_fraction': 0.7458519562366559, 
     'bagging_fraction': 0.7835116194444349, 
     'bagging_freq': 2, 
     'min_child_samples': 95,
    'n_estimators':300
}

# {'lambda_l1': 5.7529066102502985e-05, 
#  'lambda_l2': 1.3522520634637266e-08, 
#  'num_leaves': 216, 
#  'feature_fraction': 0.7458519562366559, 
#  'bagging_fraction': 0.7835116194444349, 
#  'bagging_freq': 2, 
#  'min_child_samples': 95}

In [30]:
model = LGBMClassifier(**lgbm_params)

In [31]:
model.fit(X_train, y_train)

[LightGBM] [Warning] lambda_l1 is set=5e-05, reg_alpha=0.0 will be ignored. Current value: lambda_l1=5e-05
[LightGBM] [Warning] bagging_fraction is set=0.7835116194444349, subsample=1.0 will be ignored. Current value: bagging_fraction=0.7835116194444349
[LightGBM] [Warning] lambda_l2 is set=1.35e-08, reg_lambda=0.0 will be ignored. Current value: lambda_l2=1.35e-08
[LightGBM] [Warning] boosting is set=gbdt, boosting_type=gbdt will be ignored. Current value: boosting=gbdt
[LightGBM] [Warning] feature_fraction is set=0.7458519562366559, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.7458519562366559
[LightGBM] [Warning] min_data_in_leaf is set=100, min_child_samples=95 will be ignored. Current value: min_data_in_leaf=100
[LightGBM] [Warning] bagging_freq is set=2, subsample_freq=0 will be ignored. Current value: bagging_freq=2


LGBMClassifier(application='binary', bagging_fraction=0.7835116194444349,
               bagging_freq=2, boosting='gbdt',
               feature_fraction=0.7458519562366559, lambda_l1=5e-05,
               lambda_l2=1.35e-08, learning_rate=0.02, metric='binary_logloss',
               min_child_samples=95, min_data_in_leaf=100, n_estimators=300,
               num_leaves=216)

In [32]:
# num_round = 1000
# bst = gbm.train(lgbm_params, train_data, num_round, valid_sets=[validation_data], early_stopping_rounds=10, verbose_eval=100)

In [33]:
# ?gbm.train

In [34]:
# df_test = pd.read_csv(test_path)
# df_test.head()

In [35]:
df_test2 = df_test.drop(["id", "target"], axis=1)

In [36]:
# for col in cat_col:
#     df_test2[col] = df_test2[col].apply(hash_cat_two)
#     print("done ", col)

In [37]:
# ?bst

In [38]:
df_test2.head()

cat0  cat1  cat2  cat3  cat4  cat5  cat6  cat7  cat8  cat9  ...     cont1  \
0     0     1     0     1     7    33     6    31     0     0  ...  0.832036   
1     0     8     0     0     3     2    12     8    12     0  ...  0.461403   
2     0     5     0     0     4    33     0    32    60     0  ...  0.727531   
3     1     8     5     1     5    33     0    14    45     0  ...  0.294513   
4     0    10     0     0     4    33     2    26    38     5  ...  0.354699   

      cont2     cont3     cont4     cont5     cont6     cont7     cont8  \
0  0.936027  0.277879  0.677056  0.556303  0.861982  0.880029  0.700449   
1  0.465581  0.773081  0.257367  0.118800  0.076394  0.617704  0.786615   
2  0.799496  0.792766  0.574415  0.240725  0.263741  1.005591  0.710779   
3  0.301259  0.340367  0.385370  0.555850  0.486549  0.338415  0.392193   
4  0.317978  0.590793  0.207941  0.734811  0.569722  0.569788  0.477121   

      cont9    cont10  
0  0.408714  0.457853  
1  0.463401  0.534980  
2  0.878274  0.967304  
3  0.255491  0.398400  
4  0.530924  0.349163  

[5 rows x 30 columns]

In [39]:
pred = model.predict(df_test2)

In [40]:
pred_proba = model.predict_proba(df_test2)

In [41]:
df_test2

cat0  cat1  cat2  cat3  cat4  cat5  cat6  cat7  cat8  cat9  ...  \
0          0     1     0     1     7    33     6    31     0     0  ...   
1          0     8     0     0     3     2    12     8    12     0  ...   
2          0     5     0     0     4    33     0    32    60     0  ...   
3          1     8     5     1     5    33     0    14    45     0  ...   
4          0    10     0     0     4    33     2    26    38     5  ...   
...      ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   
119995     1     8     0     0     5    33     4    40    35     0  ...   
119996     1    10     0     4     7    33     0    30    38     0  ...   
119997     0    10     0     0     4    33     2    39    38     7  ...   
119998     0     7     0     0     5    45     7    28     3     5  ...   
119999     0     5    15     2     7    33     7    27    48     0  ...   

           cont1     cont2     cont3     cont4     cont5     cont6     cont7  \
0       0.832036  0.936027  0.277879  0.677056  0.556303  0.861982  0.880029   
1       0.461403  0.465581  0.773081  0.257367  0.118800  0.076394  0.617704   
2       0.727531  0.799496  0.792766  0.574415  0.240725  0.263741  1.005591   
3       0.294513  0.301259  0.340367  0.385370  0.555850  0.486549  0.338415   
4       0.354699  0.317978  0.590793  0.207941  0.734811  0.569722  0.569788   
...          ...       ...       ...       ...       ...       ...       ...   
119995  0.460675  0.690114  0.556406  0.778571  0.280025  0.544267  0.524250   
119996  0.702119  0.698665  0.771236  0.806725  0.556306  0.339435  0.740020   
119997  0.325691  0.245823  0.243893  0.808406  0.273086  0.577464  0.283429   
119998  0.621029  0.940450  0.082610  0.238615  0.274609  0.425721  0.321446   
119999  0.838295  0.794714  0.192842  0.677982  0.781721  0.885908  0.544858   

           cont8     cont9    cont10  
0       0.700449  0.408714  0.457853  
1       0.786615  0.463401  0.534980  
2       0.710779  0.878274  0.967304  
3       0.392193  0.255491  0.398400  
4       0.477121  0.530924  0.349163  
...          ...       ...       ...  
119995  0.502416  0.782653  0.683392  
119996  0.420333  0.957234  0.777523  
119997  0.347557  0.254384  0.269322  
119998  0.323698  0.525235  0.796209  
119999  0.869808  0.340432  0.453767  

[120000 rows x 30 columns]

In [42]:
df_pred_final = df_test[["id"]]

In [43]:
df_pred_final["target"] = pred


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy


In [44]:
pred_proba[:,0]

array([0.03137987, 0.94545578, 0.94467265, ..., 0.89156603, 0.39109096,
       0.29719791])

In [45]:
df_pred_final["target_proba"] = pred_proba[:,1]


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy


In [46]:
df_pred_final.head()

id  target  target_proba
0   99402       1      0.968620
1   92026       0      0.054544
2  102280       0      0.055327
3  293468       0      0.023322
4   56800       0      0.226151

# df_pred_final.to_csv('submission.csv', index=False)

In [47]:
pred

array([1, 0, 0, ..., 0, 1, 1])

# evaluation local

In [48]:
from sklearn.metrics import roc_auc_score

In [49]:
y_test_label = df_test["target"]

In [50]:
roc_auc_score(y_test_label, pred)

0.7759849439459308

In [51]:
# local test result 
auc = 0.8969435887822527

In [52]:
roc_auc_score(y_test_label, pred_proba[:,1])

0.8915191600858575

# run shap

In [77]:
import shap

In [78]:
# explainer = shap.Explainer(model)
# shap_values = explainer(X)

In [79]:
tree_explainer = shap.TreeExplainer(model)


In [80]:
type(tree_explainer)

shap.explainers._tree.Tree

In [81]:
explainer = shap.Explainer(model)

In [82]:
type(explainer)

shap.explainers._tree.Tree

In [ ]:
shap_values_tree = tree_explainer(X_sample)

In [ ]:
shap_values_tree

In [ ]:
type(shap_values_tree)

In [ ]:
type(tree_explainer)

In [ ]:
X.head()

In [ ]:
X_sample = X.sample(1000)

In [ ]:
?explainer

In [ ]:
# shap_values[0][:1]

In [ ]:
?shap.force_plot

In [71]:
shap.force_plot(tree_explainer.expected_value[1], shap_values_tree[1][0,:], X_sample)

IndexError: index 1 is out of bounds for axis 0 with size 1

In [65]:
import xgboost

ModuleNotFoundError: No module named 'xgboost'